<?php

namespace App\Http\Controllers;

use App\Models\Guest;
use App\Models\Invitation;
use App\Models\InvitationEvent;
use App\Models\InvitationStory;
use App\Models\Theme;
use Illuminate\Support\Collection;

class ThemePreviewController extends Controller
{
    public function show(string $themeSlug)
    {
        $aliases = [
            'webtoon' => 'manga',
            'comic' => 'manga',
            'komik' => 'manga',
            'library-card' => 'library_card',
            'vintage-book' => 'library_card',
            'vintage_book' => 'library_card',
            'novel' => 'library_card',
            'buku' => 'library_card',
            'perpustakaan' => 'library_card',
            'newspaper' => 'newspaper',
            'koran' => 'newspaper',
            'breaking-news' => 'newspaper',
            'breaking_news' => 'newspaper',
            'news' => 'newspaper',
            'berita' => 'newspaper',
            'ojek-online' => 'ojek_online',
            'ojek_online' => 'ojek_online',
            'gofood' => 'ojek_online',
            'gojek' => 'ojek_online',
            'grab' => 'ojek_online',
            'delivery-order' => 'ojek_online',
            'delivery_order' => 'ojek_online',
            'ojol' => 'ojek_online',
            'buku-nikah' => 'buku_nikah',
            'buku_nikah' => 'buku_nikah',
            'kua' => 'buku_nikah',
            'dokumen-negara' => 'buku_nikah',
            'dokumen_negara' => 'buku_nikah',
            'akta-nikah' => 'buku_nikah',
            'akta_nikah' => 'buku_nikah',
            'scoreboard' => 'scoreboard',
            'papan-skor' => 'scoreboard',
            'papan_skor' => 'scoreboard',
            'arena' => 'scoreboard',
            'stadium' => 'scoreboard',
            'football' => 'scoreboard',
            'sport' => 'scoreboard',
            'match-day' => 'scoreboard',
            'surat-cinta' => 'surat_cinta',
            'surat_cinta' => 'surat_cinta',
            'love-letter' => 'surat_cinta',
            'love_letter' => 'surat_cinta',
            'kertas-buku' => 'surat_cinta',
            'kertas_buku' => 'surat_cinta',
            'surat-kaleng' => 'surat_cinta',
            'surat_kaleng' => 'surat_cinta',
            'notebook' => 'surat_cinta',
            'binder' => 'surat_cinta',
            'tabloid' => 'tabloid',
            'majalah' => 'tabloid',
            'magazine' => 'tabloid',
            'fashion' => 'tabloid',
            'y2k' => 'tabloid',
            'gossip' => 'tabloid',
            'retro-magazine' => 'tabloid',
            'vogue' => 'tabloid',
            'kai' => 'kai',
            'kai-access' => 'kai',
            'kai_access' => 'kai',
            'kereta' => 'kai',
            'kereta-api' => 'kai',
            'kereta_api' => 'kai',
            'train' => 'kai',
            'boarding-pass' => 'kai',
            'boarding_pass' => 'kai',
            'access' => 'kai',
            'crypto' => 'crypto',
            'lct' => 'crypto',
            'love-token' => 'crypto',
            'love_token' => 'crypto',
            'trading' => 'crypto',
            'binance' => 'crypto',
            'web3' => 'crypto',
            'blockchain' => 'crypto',
            'metamask' => 'crypto',
            'bitcoin' => 'crypto',
            'premier-screening' => 'premier_screening',
            'premier_screening' => 'premier_screening',
            'cinema' => 'premier_screening',
            'movie' => 'premier_screening',
            'bioskop' => 'premier_screening',
            'islamic' => 'islamic',
            'islami' => 'islamic',
            'muslim' => 'islamic',
            'nikah' => 'islamic',
            'masjid' => 'islamic',
            'claw-machine' => 'claw_machine',
            'claw_machine' => 'claw_machine',
            'love-claw-machine' => 'claw_machine',
            'love_claw_machine' => 'claw_machine',
            'mesin-capit' => 'claw_machine',
            'mesin_capit' => 'claw_machine',
            'claw' => 'claw_machine',
            'arcade-claw' => 'claw_machine',
            'snakes-and-ladders' => 'snakes_and_ladders',
            'snakes_and_ladders' => 'snakes_and_ladders',
            'snakes-ladders' => 'snakes_and_ladders',
            'snakes_ladders' => 'snakes_and_ladders',
            'ular-tangga' => 'snakes_and_ladders',
            'ular_tangga' => 'snakes_and_ladders',
            'path-to-pelaminan' => 'snakes_and_ladders',
            'path_to_pelaminan' => 'snakes_and_ladders',
            'daily-brew' => 'daily_brew',
            'daily_brew' => 'daily_brew',
            'the-daily-brew' => 'daily_brew',
            'the_daily_brew' => 'daily_brew',
            'coffee' => 'daily_brew',
            'coffee-shop' => 'daily_brew',
            'coffee_shop' => 'daily_brew',
            'kopi' => 'daily_brew',
            'deluxe-01' => 'deluxe_01',
            'deluxe_01' => 'deluxe_01',
            'deluxe01' => 'deluxe_01',
            'deluxe-02' => 'deluxe_02',
            'deluxe_02' => 'deluxe_02',
            'deluxe02' => 'deluxe_02',
            'deluxe-03' => 'deluxe_03',
            'deluxe_03' => 'deluxe_03',
            'deluxe03' => 'deluxe_03',
            'deluxe-04' => 'deluxe_04',
            'deluxe_04' => 'deluxe_04',
            'deluxe04' => 'deluxe_04',
            'deluxe-05' => 'deluxe_05',
            'deluxe_05' => 'deluxe_05',
            'deluxe05' => 'deluxe_05',
            'deluxe-editorial' => 'deluxe_01',
            'deluxe_editorial' => 'deluxe_01',
            'editorial-wedding' => 'deluxe_01',
            'editorial_wedding' => 'deluxe_01',
            'luxury-editorial' => 'deluxe_01',
            'luxury_editorial' => 'deluxe_01',
            'ljk-exam' => 'ljk_exam',
            'ljk_exam' => 'ljk_exam',
            'ujian-sekolah' => 'ljk_exam',
            'ujian_sekolah' => 'ljk_exam',
            'lembar-jawaban' => 'ljk_exam',
            'lembar_jawaban' => 'ljk_exam',
            'ljk' => 'ljk_exam',
            'un' => 'ljk_exam',
            'shopee' => 'shopee_market',
            'shopee-market' => 'shopee_market',
            'shopee_market' => 'shopee_market',
            'shoppe' => 'shopee_market',
            'shope' => 'shopee_market',
            'ecommerce' => 'shopee_market',
            'marketplace' => 'shopee_market',
            'shop-love' => 'shopee_market',
            'shoplove' => 'shopee_market',
            'marker-doodle' => 'marker_doodle',
            'marker_doodle' => 'marker_doodle',
            'marker-sketch' => 'marker_doodle',
            'marker_sketch' => 'marker_doodle',
            'spidol' => 'marker_doodle',
            'papan-tulis' => 'marker_doodle',
            'papan_tulis' => 'marker_doodle',
            'whiteboard' => 'marker_doodle',
            'sketch' => 'marker_doodle',
            'doodle' => 'marker_doodle',
            'papan-pengumuman' => 'papan_pengumuman',
            'papan_pengumuman' => 'papan_pengumuman',
            'notice-board' => 'papan_pengumuman',
            'notice_board' => 'papan_pengumuman',
            'surat-edaran' => 'papan_pengumuman',
            'surat_edaran' => 'papan_pengumuman',
            'sekolah-jadul' => 'papan_pengumuman',
            'corkboard' => 'papan_pengumuman',
            'mading' => 'papan_pengumuman',
            'eternal-flame' => 'eternal_flame',
            'eternal_flame' => 'eternal_flame',
            'the-eternal-flame' => 'eternal_flame',
            'the_eternal_flame' => 'eternal_flame',
            'lilin-doa' => 'eternal_flame',
            'lilin_doa' => 'eternal_flame',
            'lilin-doa-pengantin' => 'eternal_flame',
            'lilin_doa_pengantin' => 'eternal_flame',
            'candle' => 'eternal_flame',
            'lilin' => 'eternal_flame',
            'api-abadi' => 'eternal_flame',
            'api_abadi' => 'eternal_flame',
            'coloring' => 'coloring_love',
            'coloring-love' => 'coloring_love',
            'coloring_love' => 'coloring_love',
            'coloring-game' => 'coloring_love',
            'coloring_game' => 'coloring_love',
            'menghidupkan-warna-cinta' => 'coloring_love',
            'menghidupkan_warna_cinta' => 'coloring_love',
            'warna-cinta' => 'coloring_love',
            'warna_cinta' => 'coloring_love',
            'mewarnai' => 'coloring_love',
            'color-love' => 'coloring_love',
            'color_love' => 'coloring_love',
            'the-coloring-love' => 'coloring_love',
            'the_coloring_love' => 'coloring_love',
            'museum' => 'museum_of_us',
            'museum-of-us' => 'museum_of_us',
            'museum_of_us' => 'museum_of_us',
            'the-museum-of-us' => 'museum_of_us',
            'the_museum_of_us' => 'museum_of_us',
            'pameran-cinta' => 'museum_of_us',
            'pameran_cinta' => 'museum_of_us',
            'galeri-cinta' => 'museum_of_us',
            'galeri_cinta' => 'museum_of_us',
            'art-gallery' => 'museum_of_us',
            'art_gallery' => 'museum_of_us',
            'gallery-of-us' => 'museum_of_us',
            'gallery_of_us' => 'museum_of_us',
            'museum-perjalanan-cinta' => 'museum_of_us',
            'grocery-receipt' => 'grocery_receipt',
            'grocery_receipt' => 'grocery_receipt',
            'struk-belanja' => 'grocery_receipt',
            'struk_belanja' => 'grocery_receipt',
            'struk' => 'grocery_receipt',
            'receipt' => 'grocery_receipt',
            'supermarket' => 'grocery_receipt',
            'minimarket' => 'grocery_receipt',
            'kasir-cinta' => 'grocery_receipt',
            'kasir_cinta' => 'grocery_receipt',
            'struk-kasir' => 'grocery_receipt',
            'struk_kasir' => 'grocery_receipt',
            'nasi-padang' => 'nasi_padang',
            'nasi_padang' => 'nasi_padang',
            'padang' => 'nasi_padang',
            'rumah-makan-padang' => 'nasi_padang',
            'rumah_makan_padang' => 'nasi_padang',
            'minang' => 'nasi_padang',
            'warung-padang' => 'nasi_padang',
            'warung_padang' => 'nasi_padang',
            'restoran-padang' => 'nasi_padang',
            'restoran_padang' => 'nasi_padang',
            'ampera' => 'nasi_padang',
            'jodoh-minang' => 'nasi_padang',
            'jodoh_minang' => 'nasi_padang',
            'nasi-kapau' => 'nasi_padang',
            'slip-gaji' => 'slip_gaji',
            'slip_gaji' => 'slip_gaji',
            'slip' => 'slip_gaji',
            'payslip' => 'slip_gaji',
            'payroll' => 'slip_gaji',
            'gaji' => 'slip_gaji',
            'slip-gaji-kantor' => 'slip_gaji',
            'ktm' => 'ktm',
            'kartu-tanda-mahasiswa' => 'ktm',
            'kartu_tanda_mahasiswa' => 'ktm',
            'student-id' => 'ktm',
            'student_id' => 'ktm',
            'kampus' => 'ktm',
            'kartu-mahasiswa' => 'ktm',
            'kartu_mahasiswa' => 'ktm',
            'mahasiswa' => 'ktm',
            'jurnal-ilmiah' => 'jurnal_ilmiah',
            'jurnal_ilmiah' => 'jurnal_ilmiah',
            'jurnal' => 'jurnal_ilmiah',
            'journal' => 'jurnal_ilmiah',
            'e-library' => 'jurnal_ilmiah',
            'e_library' => 'jurnal_ilmiah',
            'library-portal' => 'jurnal_ilmiah',
            'portal-jurnal' => 'jurnal_ilmiah',
            'skripsi' => 'jurnal_ilmiah',
            'paper' => 'jurnal_ilmiah',
            'sinta' => 'jurnal_ilmiah',
            'sinta-1' => 'jurnal_ilmiah',
            'sinta_1' => 'jurnal_ilmiah',
            'sinta-indonesia' => 'jurnal_ilmiah',
            'linked-in' => 'linkedin',
            'linkedin-wedding' => 'linkedin',
            'professional-network' => 'linkedin',
            'cv-pasangan' => 'cv_pasangan',
            'curriculum-vitae' => 'cv_pasangan',
            'curriculum-vitae-pasangan' => 'cv_pasangan',
            'daftar-riwayat-hidup' => 'cv_pasangan',
            'resume-pasangan' => 'cv_pasangan',
            'ancient-scroll' => 'ancient_scroll',
            'wedding-scroll' => 'ancient_scroll',
            'gulungan-kuno' => 'ancient_scroll',
            'prasasti-cinta' => 'ancient_scroll',
            'attendance-clock' => 'attendance_clock',
            'fingerprint-attendance' => 'attendance_clock',
            'kartu-absensi' => 'attendance_clock',
            'mesin-absensi' => 'attendance_clock',
            'time-clock' => 'attendance_clock',
            'orbit-wedding' => 'orbit',
            'orbit-cinta' => 'orbit',
            'cosmic-orbit' => 'orbit',
            'google-doc' => 'google_docs',
            'google-docs' => 'google_docs',
            'google_docs' => 'google_docs',
            'shared-document' => 'google_docs',
            'shared_document' => 'google_docs',
            'dokumen-bersama' => 'google_docs',
            'dokumen_bersama' => 'google_docs',
            'buku_islami_3d' => 'buku_islami_3d',
            'buku-islami-3d' => 'buku_islami_3d',
            'buku_islami' => 'buku_islami_3d',
            'buku-islami' => 'buku_islami_3d',
            'buku-3d-islami' => 'buku_islami_3d',
            'buku_3d_islami' => 'buku_islami_3d',
            'islamic-3d' => 'buku_islami_3d',
            'islamic_3d' => 'buku_islami_3d',
            'islamic-book' => 'buku_islami_3d',
            'islamic_book' => 'buku_islami_3d',
            'uno' => 'uno',
            'kartu-uno' => 'uno',
            'kartu_uno' => 'uno',
            'uno-wedding' => 'uno',
            'uno_wedding' => 'uno',
            'uno-game' => 'uno',
            'uno_game' => 'uno',
            'uno-card' => 'uno',
            'uno_card' => 'uno',
            'wild-card' => 'uno',
            'wild_card' => 'uno',
            'tetris' => 'tetris',
            'game-tetris' => 'tetris',
            'game_tetris' => 'tetris',
            'tetris-wedding' => 'tetris',
            'tetris_wedding' => 'tetris',
            'tetris-arcade' => 'tetris',
            'tetris_arcade' => 'tetris',
            'tetromino' => 'tetris',
            'perfect-clear' => 'tetris',
            'perfect_clear' => 'tetris',
            'periodic-table' => 'periodic_table',
            'periodic_table' => 'periodic_table',
            'tabel-periodik' => 'periodic_table',
            'tabel_periodik' => 'periodic_table',
            'tabel-periodik-kimia' => 'periodic_table',
            'tabel_periodik_kimia' => 'periodic_table',
            'kimia' => 'periodic_table',
            'chemistry' => 'periodic_table',
            'periodic' => 'periodic_table',
            'unsur-kimia' => 'periodic_table',
            'unsur_kimia' => 'periodic_table',
            'laboratorium' => 'periodic_table',
            'sticker-doodle' => 'sticker_doodle',
            'sticker_doodle' => 'sticker_doodle',
            'sticker-doodling' => 'sticker_doodle',
            'sticker_doodling' => 'sticker_doodle',
            'photobooth-doodle' => 'sticker_doodle',
            'photobooth_doodle' => 'sticker_doodle',
            'photobooth' => 'sticker_doodle',
            'photobooth-wedding' => 'sticker_doodle',
            'scrapbook-doodle' => 'sticker_doodle',
            'scrapbook' => 'sticker_doodle',
            'doodle-aesthetic' => 'sticker_doodle',
            'polaroid-doodle' => 'sticker_doodle',
            'photobox-strip' => 'photobox_strip',
            'photobox_strip' => 'photobox_strip',
            'photobox' => 'photobox_strip',
            'photo-strip' => 'photobox_strip',
            'photo_strip' => 'photobox_strip',
            'photostrip' => 'photobox_strip',
            'retro-photobox' => 'photobox_strip',
            'photobox-klasik' => 'photobox_strip',
            'photobox_klasik' => 'photobox_strip',
            'gen-z-photobox' => 'photobox_strip',
            'photobooth-strip' => 'photobox_strip',
            'photobooth_strip' => 'photobox_strip',
        ];

        $effectiveSlug = $aliases[$themeSlug] ?? $themeSlug;
        $themeSlugUnderscore = str_replace('-', '_', $effectiveSlug);
        $themeSlugDash = str_replace('_', '-', $effectiveSlug);

        $theme = Theme::with('previewData')
            ->where(function ($query) use ($effectiveSlug, $themeSlugUnderscore, $themeSlugDash) {
                $query->where('view_path', 'themes.'.$effectiveSlug)
                    ->orWhere('view_path', 'themes.'.$themeSlugUnderscore)
                    ->orWhere('view_path', 'themes.'.$themeSlugDash);
            })
            ->where('is_active', true)
            ->first();

        if (! $theme && view()->exists('themes.'.$effectiveSlug)) {
            $theme = new Theme([
                'name' => ucwords(str_replace('_', ' ', $effectiveSlug)),
                'view_path' => 'themes.'.$effectiveSlug,
                'is_active' => true,
            ]);
        } elseif (! $theme) {
            abort(404);
        }

        $preview = $theme->resolvedPreviewData();

        $invitation = new Invitation([
            'title' => $preview->title,
            'cover_photo' => $preview->cover_photo,
            'music_url' => $preview->music_url,
            'show_video' => true,
            'youtube_url' => $preview->youtube_url ?? 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
            'youtube_video_id' => $preview->youtube_video_id ?: ($preview->youtube_url ? Invitation::extractYoutubeId($preview->youtube_url) : 'aqz-KE-bpKQ'),
            'timezone' => $preview->timezone ?? 'Asia/Jakarta',
            'bride_name' => $preview->bride_name,
            'bride_photo' => $preview->bride_photo,
            'groom_name' => $preview->groom_name,
            'groom_photo' => $preview->groom_photo,
            'bride_nickname' => $preview->bride_nickname,
            'groom_nickname' => $preview->groom_nickname,
            'bride_parents' => $preview->bride_parents,
            'groom_parents' => $preview->groom_parents,
            'event_date' => $preview->event_date,
            'event_time' => $preview->event_time,
            'event_time_end' => $preview->event_time_end,
            'venue_name' => $preview->venue_name,
            'venue_address' => $preview->venue_address,
            'venue_maps_url' => $preview->venue_maps_url,
            'love_story' => $preview->love_story,
            'theme' => $effectiveSlug,
            'tier' => 'gold',
            'is_active' => true,
            'slug' => 'preview',
            'gallery_photos' => $preview->gallery_photos ?? [],
            'gift_banks' => $preview->gift_banks ?? (
                $preview->gift_bank_name ? [
                    [
                        'bank_name' => $preview->gift_bank_name,
                        'account_number' => $preview->gift_bank_account,
                        'account_holder' => $preview->gift_bank_holder,
                    ],
                ] : []
            ),
            'gift_ewallets' => $preview->gift_ewallets ?? [],
            'quote_content' => $preview->quote_content,
            'quote_source' => $preview->quote_source,
            'show_rsvp' => true,
            'show_gallery' => true,
            'show_gift' => true,
            'show_stories' => true,
            'show_countdown' => true,
            'show_event_detail' => true,
            'show_quote' => true,
            'show_video' => true,
            'show_qr_checkin' => true,
            'show_comments' => true,
        ]);

        $invitation->exists = false;

        $dummyEvents = [];
        foreach ($preview->parsed_events as $eventData) {
            $event = new InvitationEvent($eventData);
            $event->exists = false;
            $dummyEvents[] = $event;
        }

        $invitation->setRelation('events', new Collection($dummyEvents));

        $dummyStories = [];
        foreach ($preview->parsed_stories as $storyData) {
            $story = new InvitationStory($storyData);
            $story->exists = false;
            $dummyStories[] = $story;
        }
        $invitation->setRelation('stories', new Collection($dummyStories));

        $guestName = request()->query('to') ?: 'Nama Tamu';

        $guest = new Guest([
            'name' => $guestName,
            'qr_code_token' => 'preview-demo-'.str_replace([' ', '.'], '', microtime()),
        ]);

        $themeView = $theme->view_path;

        if (! view()->exists($themeView)) {
            $themeView = 'themes.jawa';
        }

        return view($themeView, [
            'invitation' => $invitation,
            'guest' => $guest,
            'isPreview' => true,
        ]);
    }
}
